const SKILL_CONFIG = Object.freeze({
  MAX_SKILL_LOAD: 8,
  MAX_EQUIPPED_SKILLS: 4,
  MIN_EQUIPPED_SKILLS: 2,
  INITIAL_ABYSS_ENERGY: 4,
  MAX_ABYSS_ENERGY: 10,
  ENERGY_GAIN_PER_HAND: 1,
  SHOWDOWN_LOSER_BONUS: 1,
  MAX_BONUS_ENERGY_PER_HAND: 2,
  MAX_ACTIVE_SKILLS_PER_PHASE: 1,
  MAX_ACTIVE_SKILLS_PER_HAND: 2,
  MAX_SUCCESSFUL_CARD_EDIT_PER_HAND: 1,
  REACTION_WINDOW_MS: 2000,
  SKILL_CHOICE_TIMEOUT_MS: 8000,
  PRE_DEAL_SKILL_WINDOW_MS: 5000,
  OVERLOAD_DISCOUNT: 3,
  OVERLOAD_MIN_COST: 1,
  ADVERSITY_CHIP_RATIO: 0.4,
  ADVERSITY_HANDS_PER_ENERGY: 2,
});

const CARD_EDIT_TAGS = Object.freeze(["HOLE_EDIT", "DECK_EDIT", "BOARD_EDIT"]);

const SKILL_TAGS = Object.freeze({
  PASSIVE: "PASSIVE",
  ACTIVE: "ACTIVE",
  REACTION: "REACTION",
  INFORMATION: "INFORMATION",
  DEFENSE: "DEFENSE",
  RESOURCE: "RESOURCE",
  CONTROL: "CONTROL",
  HOLE_EDIT: "HOLE_EDIT",
  DECK_EDIT: "DECK_EDIT",
  BOARD_EDIT: "BOARD_EDIT",
  ONCE_PER_HAND: "ONCE_PER_HAND",
  ONCE_PER_GAME: "ONCE_PER_GAME",
});

module.exports = {
  SKILL_CONFIG,
  CARD_EDIT_TAGS,
  SKILL_TAGS,
};
