const SKILL_CONFIG = Object.freeze({
  MAX_SKILL_LOAD: 8,
  MAX_EQUIPPED_SKILLS: 4,
  MIN_EQUIPPED_SKILLS: 2,
  INITIAL_ABYSS_ENERGY: 4,
  MAX_ABYSS_ENERGY: 8,
  MIN_FORTUNE_ENERGY: -4,
  ENERGY_GAIN_PER_HAND: 1,
  SHOWDOWN_LOSER_BONUS: 1,
  FEAR_CONTRIBUTION_CAP: 500,
  DESPERATION_CHIP_RATIO: 0.1,
  PERCEPTION_BASE_CHANCE: 0.15,
  PERCEPTION_MAX_CHANCE: 0.4,
  PERCEPTION_TRUTH_CHANCE: 0.75,
  PERCEPTION_MAX_TRIGGERS_PER_HAND: 3,
  FORTUNE_BASE_CHANCE: 0.1,
  FORTUNE_MAX_CHANCE: 0.3,
});

const SKILL_TAGS = Object.freeze({
  PASSIVE: "PASSIVE",
  ACTIVE: "ACTIVE",
  INFORMATION: "INFORMATION",
  DEFENSE: "DEFENSE",
  RESOURCE: "RESOURCE",
  CONTROL: "CONTROL",
  SETTLEMENT: "SETTLEMENT",
  HOLE_EDIT: "HOLE_EDIT",
  DECK_EDIT: "DECK_EDIT",
  BOARD_EDIT: "BOARD_EDIT",
  SECRET: "SECRET",
  ONCE_PER_HAND: "ONCE_PER_HAND",
});

const CARD_EDIT_TAGS = Object.freeze([
  SKILL_TAGS.HOLE_EDIT,
  SKILL_TAGS.DECK_EDIT,
  SKILL_TAGS.BOARD_EDIT,
]);

module.exports = { SKILL_CONFIG, SKILL_TAGS, CARD_EDIT_TAGS };
