const SKILL_CONFIG = Object.freeze({
  MAX_SKILL_LOAD: 8,
  MAX_EQUIPPED_SKILLS: 4,
  MIN_EQUIPPED_SKILLS: 2,
  INITIAL_ABYSS_ENERGY: 4,
  MAX_ABYSS_ENERGY: 8,
  DESTINY_MAX_ABYSS_ENERGY: 10,
  PUBLIC_ENERGY_DISPLAY_CAP: 8,
  MIN_FORTUNE_ENERGY: -4,
  ENERGY_WINNER_GAIN: 0,
  ENERGY_LOSER_GAIN: 1,
  ENERGY_TIE_GAIN: 0,
  FEAR_CONTRIBUTION_CAP: 500,
  DESPERATION_CHIP_THRESHOLD: 200,
  DESPERATION_WIN_MULTIPLIER: 3,
  BLOOD_BATTLE_MULTIPLIER: 2,
  DEAD_END_FOLD_MULTIPLIER: 3,
  PROTOCOL_WIN_MULTIPLIER: 2,
  RECYCLE_REFUND_RATE: 0.5,
  COUNTER_UNUSED_REFUND: 1,
  DEEP_BREATH_RESTORE: 2,
  PERCEPTION_BASE_CHANCE: 0.25,
  PERCEPTION_MAX_CHANCE: 0.5,
  PERCEPTION_TRUTH_CHANCE: 0.75,
  PERCEPTION_MAX_TRIGGERS_PER_HAND: 3,
  FORTUNE_REWRITE_COST: 3,
  TOP_SECRET_COST: 3,
  INTEL_COST: 4,
  NULLIFY_BOARD_COST: 6,
  NULLIFY_HOLE_COST: 7,
});

const SKILL_TAGS = Object.freeze({
  PASSIVE: "PASSIVE",
  ACTIVE: "ACTIVE",
  INFORMATION: "INFORMATION",
  DEFENSE: "DEFENSE",
  RESOURCE: "RESOURCE",
  CONTROL: "CONTROL",
  SETTLEMENT: "SETTLEMENT",
  HOLE_EDIT: "HOLE_EDIT",
  DECK_EDIT: "DECK_EDIT",
  BOARD_EDIT: "BOARD_EDIT",
  SECRET: "SECRET",
  ONCE_PER_HAND: "ONCE_PER_HAND",
  PROTOCOL: "PROTOCOL",
});

const CARD_EDIT_TAGS = Object.freeze([
  SKILL_TAGS.HOLE_EDIT,
  SKILL_TAGS.DECK_EDIT,
  SKILL_TAGS.BOARD_EDIT,
]);

const PROTOCOL_CATEGORIES = Object.freeze({
  HIGH_CARD: 1,
  PAIR: 2,
  TWO_PAIR: 3,
  TRIPS: 4,
  STRAIGHT: 5,
  FLUSH: 6,
  FULL_HOUSE: 7,
  QUADS: 8,
  STRAIGHT_FLUSH: 9,
});

module.exports = {
  SKILL_CONFIG,
  SKILL_TAGS,
  CARD_EDIT_TAGS,
  PROTOCOL_CATEGORIES,
};
